### ISSUE TITLE
[bug] Power Word + Thrice Spoken

### ISSUE THREAD

**Issue by derornos** [zzorba/ArkhamCards#415]
![image](https://user-images.githubusercontent.com/15874357/190947948-d0ca625a-7ffe-4eef-b818-a3f783321d79.png)

It's good.

![image](https://user-images.githubusercontent.com/15874357/190948000-bcf3c924-e637-47c1-8328-55ae8b9957fd.png)

but I couldn't select that button on this screen.

**Comment by zzorba** [comment]
This if fixed now, will be released soon on iOS

**Comment by derornos** [comment]
thanks~

**Comment by derornos** [comment]
https://user-images.githubusercontent.com/15874357/191633717-85464a13-adf9-4b36-8d27-d4b64e83210f.mp4

It seems to me that the problem is still unresolved...
